#! /usr/bin/env -S sh

t_flag=0
LW_PROJECT_NAME=''

print_usage() {
	echo "backup: Create backups for lawallet persistent volumes";
	echo "Usage: backup [-h] [-t project_name] BACKUP_DIRECTORY"
    echo "\t-h: print this help message and exit";
    echo "\t-t project_name: name to prepend to container names";
	echo "Examples:";
	echo "\t./backup /home/lawallet/backups"
	echo "\t./backup -t tmp_env /home/lawallet/tmp_env_backups"
}

while getopts "ht:" flag; do
    case "${flag}" in
        h) print_usage
            exit 0;;
        t)  t_flag=1
            LW_PROJECT_NAME="${OPTARG}";;
        *) print_usage
            exit 1;
    esac
done;

if [ $(( $# - $OPTIND )) -lt 0 ]; then
	print_usage
    exit 1;
fi

shift $(($OPTIND - 1))
backup_dir="$1"
current_time="$(date +%Y%m%d%H%M%S)";

backup() {
	if [ ${t_flag} -eq 0 ]; then
		container_name=$1;
	else
		container_name="${LW_PROJECT_NAME}-$1-1";
	fi;
	from_path="$2";

	echo "Backing up ${container_name}";
	backup_filename="${current_time}_${container_name}.tar.gz"
	docker run 								\
		--rm								\
		--volumes-from ${container_name} 	\
		-v ${backup_dir}:/backups 			\
		ubuntu								\
		tar czf /backups/${backup_filename} ${from_path};
	echo "Done, you can find it in ${backup_dir}/${backup_filename}";
}

backup "nostream-db" "/var/lib/postgresql/data";
backup "ledger-db" "/var/lib/postgresql/data";
backup "card-db" "/var/lib/postgresql/data";
backup "nostream-cache" "/data";
backup "urlx-cache" "/data";
