#! /usr/bin/env -S sh

set -eu;

export LC_ALL=C;

printf "This will reset the development environment, are you sure? [y/N] ";
IFS='' read -r REPLY;
if [ "${REPLY}" != 'y' ] && [ "${REPLY}" != 'Y' ]; then
    echo "Cancelled.";
    exit;
fi

HERE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)";

rm -f "${HERE}/.env";
rm -f "${HERE}/.seeded";
rm -f "${HERE}/nostream/.nostr/settings.yaml";
rm -rf "${HERE}/lnbits/data";

echo "Done.";
