#! /usr/bin/env -S sh


print_usage() {
	echo "restore_backup: Restore a backup for lawallet persistent volumes";
	echo "Usage: restore_backup [-h] [-t priject_name] CONTAINER_NAME BACKUP_FILE_PATH"
    echo "\t-h: print this help message and exit";
	echo "Example:";
	echo "\t./restore_backup card-db /home/lawallet/backups/123456789_card-db.tar.gz"
}

while getopts "ht:" flag; do
    case "${flag}" in
        h) print_usage
            exit 0;;
        *) print_usage
            exit 1;
    esac
done;

if [ $(( $# - $OPTIND )) -lt 1 ]; then
	print_usage
	exit 1;
fi;

container_name="$1";
backup_path="$2";
backup_dir="$(dirname ${backup_path})";
backup_filename="$(basename ${backup_path})";

echo "Stopping ${container_name}";
docker stop ${container_name};
echo "Restoring backup from ${backup_path}";
docker run 								\
	--rm 								\
	--volumes-from ${container_name}	\
   	-v ${backup_dir}:/backups 		\
   	ubuntu 								\
   	bash -c "cd / && tar xzf /backups/${backup_filename}";
echo "Backup restored, you may restart the container manually";
